# Generated by Django 5.2.7 on 2025-10-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="وصف المنتج"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/", verbose_name="صورة المنتج"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="size_ml",
            field=models.PositiveIntegerField(
                default=100,
                help_text="اكتب الحجم بالملي، مثل 50 أو 100",
                verbose_name="الحجم (مل)",
            ),
        ),
    ]
