# Generated by Django 5.2.7 on 2025-10-21 15:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_description_product_image_product_size_ml"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="صورة المنتج"
            ),
        ),
    ]
