# Generated by Django 5.2.7 on 2025-10-22 13:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "منتج",
                "verbose_name_plural": "المنتجات",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="تاريخ الإضافة",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="أدخل وصفًا موجزًا يوضح مميزات العطر.",
                max_length=500,
                null=True,
                verbose_name="وصف المنتج",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="السعر (ر.س)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="size_ml",
            field=models.PositiveIntegerField(
                default=100, help_text="مثلاً: 50 أو 100", verbose_name="الحجم (مل)"
            ),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(max_length=40, verbose_name="مفتاح الجلسة"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="الكمية"),
                ),
                (
                    "added_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإضافة"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="shop.product",
                        verbose_name="المنتج",
                    ),
                ),
            ],
            options={
                "verbose_name": "عنصر في السلة",
                "verbose_name_plural": "عناصر السلة",
                "ordering": ["-added_at"],
            },
        ),
    ]
